# -*- coding: utf-8 -*-
"""Exercicio 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11WUR_hlYp7s23Tkm1MLGl_8nleqCYUjK
"""

def argumento(numero1):
  if numero1 > 0:
    print('P')
  else:
      print('N')

argumento(-1)