# -*- coding: utf-8 -*-
"""Exercicio 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11WUR_hlYp7s23Tkm1MLGl_8nleqCYUjK
"""

def triangulo (n: int):
  for linha in range(1, n + 1):
    for coluna in range(1, linha + 1):
      print(coluna, end = '   ')
    print('')

triangulo(4)