# -*- coding: utf-8 -*-
"""Exercicio 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wTFWA4WeVHSeWtgDLWZICN95aBduqHBD
"""

def triangulo (n: int):
  for i in range(1, n + 1):
    for _ in range(i):
      print(i, end = '   ')
    print('')

print('Triangulo com 1')
triangulo(1)
print('Triangulo com 2')
triangulo(2)
print('Triangulo com 3')
triangulo(3)