# -*- coding: utf-8 -*-
"""Exercicio 03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11WUR_hlYp7s23Tkm1MLGl_8nleqCYUjK
"""

def argumentos(numero1, numero2, numero3):
  soma_arg = numero1 + numero2 + numero3
  print(soma_arg)
  

argumentos(7,3,5)