# -*- coding: utf-8 -*-
"""Exercicio 03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nEgQF_7kx_yyVk6CjLKK76gGebrjSIwH
"""

nome = str(input('Digite seu nome: '))
idade = int(input('Digite sua idade: '))
salario = float(input('Digite seu salário: '))
sexo = str(input('Digite seu sexo: '))
estado_civil = str(input('Digite seu estado civil: '))

while (len(nome) <= 3):
  print('O nome deve ter acima de 3 caractéres')
  break
while 0<= idade >= 150:
  print('Por favor, digite uma idade correta')
  break
while salario <= 0:
  print('Digite um salário válido')
  break
while sexo != ('f', 'm'):
  print('Digite um sexo válido')
  break
while estado_civil != ('s', 'c', 'v', 'd'):
  print('Digite um estado civil válido')
  break