# -*- coding: utf-8 -*-
"""Exercicio 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nEgQF_7kx_yyVk6CjLKK76gGebrjSIwH
"""

nome = str(input('Digite um usuário: '))
senha = str(input('Digite uma senha: '))

while nome == senha:
  print("""'O usuário e a senha não podem ser iguais' 
'Por favor, insira um login válido.'""")
  
  break