# -*- coding: utf-8 -*-
"""Exercicio 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yxrb3qhy5iTnRT97aM5dQAYI2KSTBfOc
"""

nome = []
nome = str.upper(input('Digite seu nome: '))
print(nome[::-1])