# -*- coding: utf-8 -*-
"""Exercicio 03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4p_wWvHddxGxbiMlIBuas_8LaASoZSL
"""

sexo = str(input('Qual seu sexo? ').upper())


if sexo == 'M':
  print('Masculino')

elif sexo == 'F':
  print('Feminino')

else:
  print('Sexo inválido')