# -*- coding: utf-8 -*-
"""Exercicio 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lDId2ft7njYqufHYCeCXFEGTYbUXgy5r
"""

alfa = input("Informe uma letra ou consoante:")

if alfa.isalpha():
    if alfa =="a":
        print("Vogal")
    elif alfa == "e":
        print("Vogal")
    elif alfa == "i":
        print("Vogal")
    elif alfa == "o":
        print("Vogal")
    elif alfa == "u":
        print("Vogal")
    else:
        print("Consoante")
else:
    print("Não é uma letra!")

