# -*- coding: utf-8 -*-
"""Exercicio 06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_LXa9q1gXygOMv4NpBY_WyHTIT7MVMf
"""

n1 = int(input('O primeiro numero é '))
n2 = int(input('O segundo numero é '))
n3 = int(input('O terceiro numero é '))

if n1 > n2 and n3:
  print(f'O maior numero é {n1}')
  if n2 > n1 and n3:
   print(f'O maior numero é {n2}')
else:
   n3 > n1 and n3
   print(f'O maior numero é {n3}')