# -*- coding: utf-8 -*-
"""Exercício 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PfLKdLnGu0BOD8XfM-ZNBwM5uV5c34EP
"""

a = int(input('O primeiro numero é '))
b = int(input('O segundo numero é '))

if a > b:
  print(f'O numero {a} é maior.')

if b > a:
    print(f'O numero {b} é maior.')

else:
    print(f'Os numeros são iguais.')